    # See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: requirements-txt-fixer
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: debug-statements
    - id: check-merge-conflict

-   repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.1.1
    hooks:
    - id: black
      language: python
      types: [python]
      args:
        - --line-length=79

-   repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
    - id: flake8
      language: python
      args:
        - "--max-line-length=79"
        - "--doctests"
        - "--extend-ignore=E203,F405, F403"

        # docs/make.py

# -   repo: https://github.com/PyCQA/flake8-docstrings
#     rev: 1.6.0
#     hooks:
#     - id: flake8-docstrings
#       language: python
#       args:
#         - "--docstring-convention=numpy"
#       exclude: ^python/DaMAT2beremoved.py

-   repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
    - id: clang-format
